version:      0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file sam.yaml --s3-bucket vino-sam-build --output-template-file output_sam.yaml
artifacts:
  type:       zip
  files:
    - output_sam.yaml
