version:      0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - cd $CODEBUILD_SRC_DIR/layers/layer_node/nodejs/
      - npm install
artifacts:
  files:
    - layers/layer_node/**/*
    - getAllWines/**/*
    - buildspec-sam.yml
    - sam.yaml
