AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-vino-lambda
  Sample SAM Template for vino-api

Parameters:
  CertificateArn:
    Type: String
  CognitoPoolArn:
    Type: String
  DomainName:
    Type: String
  DbUser:
    Type: String
  DbPass:
    Type: String
  DbCluster:
    Type: String
  HostedZoneId:
    Type: String

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x
    Tracing: Active


Resources:
  # API
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: Wines
      StageName: Prod
      EndpointConfiguration: EDGE
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Access-Control-Allow-Origin,Access-Control-Allow-Credentials'"
      GatewayResponses:
        DEFAULT_4XX:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
      Auth:
        DefaultAuthorizer: DefaultCognitoAuthorizer
        Authorizers:
          DefaultCognitoAuthorizer:
            UserPoolArn: !Ref CognitoPoolArn
      TracingEnabled: true

  ApiDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      EndpointConfiguration:
        Types:
          - EDGE
      CertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName

  ApiBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref Api
      Stage: Prod


  # Lambda Functions / Endpoints
  GetAllWines:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetAllWines
      CodeUri: getAllWines
      Handler: get.handler
      Timeout: 15
      Environment:
        Variables:
          DBPASS: !Ref DbPass
          DBCLUSTER: !Ref DbCluster
          DBUSER: !Ref DbUser
      Layers:
        - !Ref CommonNodeLayer
      Policies:
        - CloudWatchLogsFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /wines
            Method: get
            RestApiId: !Ref Api

  CommonNodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CommonNode
      Description: Common code for NodeJS
      ContentUri: layers/layer_node/
      CompatibleRuntimes:
        - nodejs10.x
      RetentionPolicy: Retain

  DomainNameRoute53RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref ApiDomainName
          Type : A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt ApiDomainName.DistributionDomainName
